export interface CSSInJSProperties {
	[key: string]: string | undefined

	msAccelerator?: string
	msBlockProgression?: string
	msContentZoomChaining?: string
	msContentZooming?: string
	msContentZoomLimit?: string
	msContentZoomLimitMax?: string
	msContentZoomLimitMin?: string
	msContentZoomSnap?: string
	msContentZoomSnapPoints?: string
	msContentZoomSnapType?: string
	msFilter?: string
	msFlowFrom?: string
	msFlowInto?: string
	msGridColumns?: string
	msGridRows?: string
	msHighContrastAdjust?: string
	msHyphenateLimitChars?: string
	msHyphenateLimitLines?: string
	msHyphenateLimitZone?: string
	msImeAlign?: string
	msOverflowStyle?: string
	msScrollbar3dlightColor?: string
	msScrollbarArrowColor?: string
	msScrollbarBaseColor?: string
	msScrollbarDarkshadowColor?: string
	msScrollbarFaceColor?: string
	msScrollbarHighlightColor?: string
	msScrollbarShadowColor?: string
	msScrollbarTrackColor?: string
	msScrollChaining?: string
	msScrollLimit?: string
	msScrollLimitXMax?: string
	msScrollLimitXMin?: string
	msScrollLimitYMax?: string
	msScrollLimitYMin?: string
	msScrollRails?: string
	msScrollSnapPointsX?: string
	msScrollSnapPointsY?: string
	msScrollSnapType?: string
	msScrollSnapX?: string
	msScrollSnapY?: string
	msScrollTranslation?: string
	msTextAutospace?: string
	msTouchSelect?: string
	msUserSelect?: string
	msWrapFlow?: string
	msWrapMargin?: string
	msWrapThrough?: string
	MozAppearance?: string
	MozBinding?: string
	MozBorderBottomColors?: string
	MozBorderLeftColors?: string
	MozBorderRightColors?: string
	MozBorderTopColors?: string
	MozContextProperties?: string
	MozFloatEdge?: string
	MozForceBrokenImageIcon?: string
	MozImageRegion?: string
	MozOrient?: string
	MozOutlineRadius?: string
	MozOutlineRadiusBottomleft?: string
	MozOutlineRadiusBottomright?: string
	MozOutlineRadiusTopleft?: string
	MozOutlineRadiusTopright?: string
	MozStackSizing?: string
	MozTextBlink?: string
	MozUserFocus?: string
	MozUserInput?: string
	MozUserModify?: string
	MozWindowDragging?: string
	MozWindowShadow?: string
	WebkitAppearance?: string
	WebkitBorderBefore?: string
	WebkitBorderBeforeColor?: string
	WebkitBorderBeforeStyle?: string
	WebkitBorderBeforeWidth?: string
	WebkitBoxReflect?: string
	WebkitLineClamp?: string
	WebkitMask?: string
	WebkitMaskAttachment?: string
	WebkitMaskClip?: string
	WebkitMaskComposite?: string
	WebkitMaskImage?: string
	WebkitMaskOrigin?: string
	WebkitMaskPosition?: string
	WebkitMaskPositionX?: string
	WebkitMaskPositionY?: string
	WebkitMaskRepeat?: string
	WebkitMaskRepeatX?: string
	WebkitMaskRepeatY?: string
	WebkitMaskSize?: string
	WebkitOverflowScrolling?: string
	WebkitTapHighlightColor?: string
	WebkitTextFillColor?: string
	WebkitTextStroke?: string
	WebkitTextStrokeColor?: string
	WebkitTextStrokeWidth?: string
	WebkitTouchCallout?: string
	WebkitUserModify?: string
	alignContent?: string
	alignItems?: string
	alignSelf?: string
	alignTracks?: string
	all?: string
	animation?: string
	animationDelay?: string
	animationDirection?: string
	animationDuration?: string
	animationFillMode?: string
	animationIterationCount?: string
	animationName?: string
	animationPlayState?: string
	animationTimingFunction?: string
	appearance?: string
	aspectRatio?: string
	azimuth?: string
	backdropFilter?: string
	backfaceVisibility?: string
	background?: string
	backgroundAttachment?: string
	backgroundBlendMode?: string
	backgroundClip?: string
	backgroundColor?: string
	backgroundImage?: string
	backgroundOrigin?: string
	backgroundPosition?: string
	backgroundPositionX?: string
	backgroundPositionY?: string
	backgroundRepeat?: string
	backgroundSize?: string
	blockOverflow?: string
	blockSize?: string
	border?: string
	borderBlock?: string
	borderBlockColor?: string
	borderBlockStyle?: string
	borderBlockWidth?: string
	borderBlockEnd?: string
	borderBlockEndColor?: string
	borderBlockEndStyle?: string
	borderBlockEndWidth?: string
	borderBlockStart?: string
	borderBlockStartColor?: string
	borderBlockStartStyle?: string
	borderBlockStartWidth?: string
	borderBottom?: string
	borderBottomColor?: string
	borderBottomLeftRadius?: string
	borderBottomRightRadius?: string
	borderBottomStyle?: string
	borderBottomWidth?: string
	borderCollapse?: string
	borderColor?: string
	borderEndEndRadius?: string
	borderEndStartRadius?: string
	borderImage?: string
	borderImageOutset?: string
	borderImageRepeat?: string
	borderImageSlice?: string
	borderImageSource?: string
	borderImageWidth?: string
	borderInline?: string
	borderInlineEnd?: string
	borderInlineColor?: string
	borderInlineStyle?: string
	borderInlineWidth?: string
	borderInlineEndColor?: string
	borderInlineEndStyle?: string
	borderInlineEndWidth?: string
	borderInlineStart?: string
	borderInlineStartColor?: string
	borderInlineStartStyle?: string
	borderInlineStartWidth?: string
	borderLeft?: string
	borderLeftColor?: string
	borderLeftStyle?: string
	borderLeftWidth?: string
	borderRadius?: string
	borderRight?: string
	borderRightColor?: string
	borderRightStyle?: string
	borderRightWidth?: string
	borderSpacing?: string
	borderStartEndRadius?: string
	borderStartStartRadius?: string
	borderStyle?: string
	borderTop?: string
	borderTopColor?: string
	borderTopLeftRadius?: string
	borderTopRightRadius?: string
	borderTopStyle?: string
	borderTopWidth?: string
	borderWidth?: string
	bottom?: string
	boxAlign?: string
	boxDecorationBreak?: string
	boxDirection?: string
	boxFlex?: string
	boxFlexGroup?: string
	boxLines?: string
	boxOrdinalGroup?: string
	boxOrient?: string
	boxPack?: string
	boxShadow?: string
	boxSizing?: string
	breakAfter?: string
	breakBefore?: string
	breakInside?: string
	captionSide?: string
	caretColor?: string
	clear?: string
	clip?: string
	clipPath?: string
	color?: string
	colorAdjust?: string
	colorScheme?: string
	columnCount?: string
	columnFill?: string
	columnGap?: string
	columnRule?: string
	columnRuleColor?: string
	columnRuleStyle?: string
	columnRuleWidth?: string
	columnSpan?: string
	columnWidth?: string
	columns?: string
	contain?: string
	content?: string
	contentVisibility?: string
	counterIncrement?: string
	counterReset?: string
	counterSet?: string
	cursor?: string
	direction?: string
	display?: string
	emptyCells?: string
	filter?: string
	flex?: string
	flexBasis?: string
	flexDirection?: string
	flexFlow?: string
	flexGrow?: string
	flexShrink?: string
	flexWrap?: string
	float?: string
	font?: string
	fontFamily?: string
	fontFeatureSettings?: string
	fontKerning?: string
	fontLanguageOverride?: string
	fontOpticalSizing?: string
	fontVariationSettings?: string
	fontSize?: string
	fontSizeAdjust?: string
	fontSmooth?: string
	fontStretch?: string
	fontStyle?: string
	fontSynthesis?: string
	fontVariant?: string
	fontVariantAlternates?: string
	fontVariantCaps?: string
	fontVariantEastAsian?: string
	fontVariantLigatures?: string
	fontVariantNumeric?: string
	fontVariantPosition?: string
	fontWeight?: string
	forcedColorAdjust?: string
	gap?: string
	grid?: string
	gridArea?: string
	gridAutoColumns?: string
	gridAutoFlow?: string
	gridAutoRows?: string
	gridColumn?: string
	gridColumnEnd?: string
	gridColumnGap?: string
	gridColumnStart?: string
	gridGap?: string
	gridRow?: string
	gridRowEnd?: string
	gridRowGap?: string
	gridRowStart?: string
	gridTemplate?: string
	gridTemplateAreas?: string
	gridTemplateColumns?: string
	gridTemplateRows?: string
	hangingPunctuation?: string
	height?: string
	hyphens?: string
	imageOrientation?: string
	imageRendering?: string
	imageResolution?: string
	imeMode?: string
	initialLetter?: string
	initialLetterAlign?: string
	inlineSize?: string
	inset?: string
	insetBlock?: string
	insetBlockEnd?: string
	insetBlockStart?: string
	insetInline?: string
	insetInlineEnd?: string
	insetInlineStart?: string
	isolation?: string
	justifyContent?: string
	justifyItems?: string
	justifySelf?: string
	justifyTracks?: string
	left?: string
	letterSpacing?: string
	lineBreak?: string
	lineClamp?: string
	lineHeight?: string
	lineHeightStep?: string
	listStyle?: string
	listStyleImage?: string
	listStylePosition?: string
	listStyleType?: string
	margin?: string
	marginBlock?: string
	marginBlockEnd?: string
	marginBlockStart?: string
	marginBottom?: string
	marginInline?: string
	marginInlineEnd?: string
	marginInlineStart?: string
	marginLeft?: string
	marginRight?: string
	marginTop?: string
	marginTrim?: string
	mask?: string
	maskBorder?: string
	maskBorderMode?: string
	maskBorderOutset?: string
	maskBorderRepeat?: string
	maskBorderSlice?: string
	maskBorderSource?: string
	maskBorderWidth?: string
	maskClip?: string
	maskComposite?: string
	maskImage?: string
	maskMode?: string
	maskOrigin?: string
	maskPosition?: string
	maskRepeat?: string
	maskSize?: string
	maskType?: string
	masonryAutoFlow?: string
	mathStyle?: string
	maxBlockSize?: string
	maxHeight?: string
	maxInlineSize?: string
	maxLines?: string
	maxWidth?: string
	minBlockSize?: string
	minHeight?: string
	minInlineSize?: string
	minWidth?: string
	mixBlendMode?: string
	objectFit?: string
	objectPosition?: string
	offset?: string
	offsetAnchor?: string
	offsetDistance?: string
	offsetPath?: string
	offsetPosition?: string
	offsetRotate?: string
	opacity?: string
	order?: string
	orphans?: string
	outline?: string
	outlineColor?: string
	outlineOffset?: string
	outlineStyle?: string
	outlineWidth?: string
	overflow?: string
	overflowAnchor?: string
	overflowBlock?: string
	overflowClipBox?: string
	overflowClipMargin?: string
	overflowInline?: string
	overflowWrap?: string
	overflowX?: string
	overflowY?: string
	overscrollBehavior?: string
	overscrollBehaviorBlock?: string
	overscrollBehaviorInline?: string
	overscrollBehaviorX?: string
	overscrollBehaviorY?: string
	padding?: string
	paddingBlock?: string
	paddingBlockEnd?: string
	paddingBlockStart?: string
	paddingBottom?: string
	paddingInline?: string
	paddingInlineEnd?: string
	paddingInlineStart?: string
	paddingLeft?: string
	paddingRight?: string
	paddingTop?: string
	pageBreakAfter?: string
	pageBreakBefore?: string
	pageBreakInside?: string
	paintOrder?: string
	perspective?: string
	perspectiveOrigin?: string
	placeContent?: string
	placeItems?: string
	placeSelf?: string
	pointerEvents?: string
	position?: string
	quotes?: string
	resize?: string
	right?: string
	rotate?: string
	rowGap?: string
	rubyAlign?: string
	rubyMerge?: string
	rubyPosition?: string
	scale?: string
	scrollbarColor?: string
	scrollbarGutter?: string
	scrollbarWidth?: string
	scrollBehavior?: string
	scrollMargin?: string
	scrollMarginBlock?: string
	scrollMarginBlockStart?: string
	scrollMarginBlockEnd?: string
	scrollMarginBottom?: string
	scrollMarginInline?: string
	scrollMarginInlineStart?: string
	scrollMarginInlineEnd?: string
	scrollMarginLeft?: string
	scrollMarginRight?: string
	scrollMarginTop?: string
	scrollPadding?: string
	scrollPaddingBlock?: string
	scrollPaddingBlockStart?: string
	scrollPaddingBlockEnd?: string
	scrollPaddingBottom?: string
	scrollPaddingInline?: string
	scrollPaddingInlineStart?: string
	scrollPaddingInlineEnd?: string
	scrollPaddingLeft?: string
	scrollPaddingRight?: string
	scrollPaddingTop?: string
	scrollSnapAlign?: string
	scrollSnapCoordinate?: string
	scrollSnapDestination?: string
	scrollSnapPointsX?: string
	scrollSnapPointsY?: string
	scrollSnapStop?: string
	scrollSnapType?: string
	scrollSnapTypeX?: string
	scrollSnapTypeY?: string
	shapeImageThreshold?: string
	shapeMargin?: string
	shapeOutside?: string
	tabSize?: string
	tableLayout?: string
	textAlign?: string
	textAlignLast?: string
	textCombineUpright?: string
	textDecoration?: string
	textDecorationColor?: string
	textDecorationLine?: string
	textDecorationSkip?: string
	textDecorationSkipInk?: string
	textDecorationStyle?: string
	textDecorationThickness?: string
	textEmphasis?: string
	textEmphasisColor?: string
	textEmphasisPosition?: string
	textEmphasisStyle?: string
	textIndent?: string
	textJustify?: string
	textOrientation?: string
	textOverflow?: string
	textRendering?: string
	textShadow?: string
	textSizeAdjust?: string
	textTransform?: string
	textUnderlineOffset?: string
	textUnderlinePosition?: string
	top?: string
	touchAction?: string
	transform?: string
	transformBox?: string
	transformOrigin?: string
	transformStyle?: string
	transition?: string
	transitionDelay?: string
	transitionDuration?: string
	transitionProperty?: string
	transitionTimingFunction?: string
	translate?: string
	unicodeBidi?: string
	userSelect?: string
	verticalAlign?: string
	visibility?: string
	whiteSpace?: string
	widows?: string
	width?: string
	willChange?: string
	wordBreak?: string
	wordSpacing?: string
	wordWrap?: string
	writingMode?: string
	zIndex?: string
	zoom?: string
}
