export interface CSSProperties {
	[key: string]: string | undefined

	'-ms-accelerator'?: string
	'-ms-block-progression'?: string
	'-ms-content-zoom-chaining'?: string
	'-ms-content-zooming'?: string
	'-ms-content-zoom-limit'?: string
	'-ms-content-zoom-limit-max'?: string
	'-ms-content-zoom-limit-min'?: string
	'-ms-content-zoom-snap'?: string
	'-ms-content-zoom-snap-points'?: string
	'-ms-content-zoom-snap-type'?: string
	'-ms-filter'?: string
	'-ms-flow-from'?: string
	'-ms-flow-into'?: string
	'-ms-grid-columns'?: string
	'-ms-grid-rows'?: string
	'-ms-high-contrast-adjust'?: string
	'-ms-hyphenate-limit-chars'?: string
	'-ms-hyphenate-limit-lines'?: string
	'-ms-hyphenate-limit-zone'?: string
	'-ms-ime-align'?: string
	'-ms-overflow-style'?: string
	'-ms-scrollbar-3dlight-color'?: string
	'-ms-scrollbar-arrow-color'?: string
	'-ms-scrollbar-base-color'?: string
	'-ms-scrollbar-darkshadow-color'?: string
	'-ms-scrollbar-face-color'?: string
	'-ms-scrollbar-highlight-color'?: string
	'-ms-scrollbar-shadow-color'?: string
	'-ms-scrollbar-track-color'?: string
	'-ms-scroll-chaining'?: string
	'-ms-scroll-limit'?: string
	'-ms-scroll-limit-x-max'?: string
	'-ms-scroll-limit-x-min'?: string
	'-ms-scroll-limit-y-max'?: string
	'-ms-scroll-limit-y-min'?: string
	'-ms-scroll-rails'?: string
	'-ms-scroll-snap-points-x'?: string
	'-ms-scroll-snap-points-y'?: string
	'-ms-scroll-snap-type'?: string
	'-ms-scroll-snap-x'?: string
	'-ms-scroll-snap-y'?: string
	'-ms-scroll-translation'?: string
	'-ms-text-autospace'?: string
	'-ms-touch-select'?: string
	'-ms-user-select'?: string
	'-ms-wrap-flow'?: string
	'-ms-wrap-margin'?: string
	'-ms-wrap-through'?: string
	'-moz-appearance'?: string
	'-moz-binding'?: string
	'-moz-border-bottom-colors'?: string
	'-moz-border-left-colors'?: string
	'-moz-border-right-colors'?: string
	'-moz-border-top-colors'?: string
	'-moz-context-properties'?: string
	'-moz-float-edge'?: string
	'-moz-force-broken-image-icon'?: string
	'-moz-image-region'?: string
	'-moz-orient'?: string
	'-moz-outline-radius'?: string
	'-moz-outline-radius-bottomleft'?: string
	'-moz-outline-radius-bottomright'?: string
	'-moz-outline-radius-topleft'?: string
	'-moz-outline-radius-topright'?: string
	'-moz-stack-sizing'?: string
	'-moz-text-blink'?: string
	'-moz-user-focus'?: string
	'-moz-user-input'?: string
	'-moz-user-modify'?: string
	'-moz-window-dragging'?: string
	'-moz-window-shadow'?: string
	'-webkit-appearance'?: string
	'-webkit-border-before'?: string
	'-webkit-border-before-color'?: string
	'-webkit-border-before-style'?: string
	'-webkit-border-before-width'?: string
	'-webkit-box-reflect'?: string
	'-webkit-line-clamp'?: string
	'-webkit-mask'?: string
	'-webkit-mask-attachment'?: string
	'-webkit-mask-clip'?: string
	'-webkit-mask-composite'?: string
	'-webkit-mask-image'?: string
	'-webkit-mask-origin'?: string
	'-webkit-mask-position'?: string
	'-webkit-mask-position-x'?: string
	'-webkit-mask-position-y'?: string
	'-webkit-mask-repeat'?: string
	'-webkit-mask-repeat-x'?: string
	'-webkit-mask-repeat-y'?: string
	'-webkit-mask-size'?: string
	'-webkit-overflow-scrolling'?: string
	'-webkit-tap-highlight-color'?: string
	'-webkit-text-fill-color'?: string
	'-webkit-text-stroke'?: string
	'-webkit-text-stroke-color'?: string
	'-webkit-text-stroke-width'?: string
	'-webkit-touch-callout'?: string
	'-webkit-user-modify'?: string
	'align-content'?: string
	'align-items'?: string
	'align-self'?: string
	'align-tracks'?: string
	all?: string
	animation?: string
	'animation-delay'?: string
	'animation-direction'?: string
	'animation-duration'?: string
	'animation-fill-mode'?: string
	'animation-iteration-count'?: string
	'animation-name'?: string
	'animation-play-state'?: string
	'animation-timing-function'?: string
	appearance?: string
	'aspect-ratio'?: string
	azimuth?: string
	'backdrop-filter'?: string
	'backface-visibility'?: string
	background?: string
	'background-attachment'?: string
	'background-blend-mode'?: string
	'background-clip'?: string
	'background-color'?: string
	'background-image'?: string
	'background-origin'?: string
	'background-position'?: string
	'background-position-x'?: string
	'background-position-y'?: string
	'background-repeat'?: string
	'background-size'?: string
	'block-overflow'?: string
	'block-size'?: string
	border?: string
	'border-block'?: string
	'border-block-color'?: string
	'border-block-style'?: string
	'border-block-width'?: string
	'border-block-end'?: string
	'border-block-end-color'?: string
	'border-block-end-style'?: string
	'border-block-end-width'?: string
	'border-block-start'?: string
	'border-block-start-color'?: string
	'border-block-start-style'?: string
	'border-block-start-width'?: string
	'border-bottom'?: string
	'border-bottom-color'?: string
	'border-bottom-left-radius'?: string
	'border-bottom-right-radius'?: string
	'border-bottom-style'?: string
	'border-bottom-width'?: string
	'border-collapse'?: string
	'border-color'?: string
	'border-end-end-radius'?: string
	'border-end-start-radius'?: string
	'border-image'?: string
	'border-image-outset'?: string
	'border-image-repeat'?: string
	'border-image-slice'?: string
	'border-image-source'?: string
	'border-image-width'?: string
	'border-inline'?: string
	'border-inline-end'?: string
	'border-inline-color'?: string
	'border-inline-style'?: string
	'border-inline-width'?: string
	'border-inline-end-color'?: string
	'border-inline-end-style'?: string
	'border-inline-end-width'?: string
	'border-inline-start'?: string
	'border-inline-start-color'?: string
	'border-inline-start-style'?: string
	'border-inline-start-width'?: string
	'border-left'?: string
	'border-left-color'?: string
	'border-left-style'?: string
	'border-left-width'?: string
	'border-radius'?: string
	'border-right'?: string
	'border-right-color'?: string
	'border-right-style'?: string
	'border-right-width'?: string
	'border-spacing'?: string
	'border-start-end-radius'?: string
	'border-start-start-radius'?: string
	'border-style'?: string
	'border-top'?: string
	'border-top-color'?: string
	'border-top-left-radius'?: string
	'border-top-right-radius'?: string
	'border-top-style'?: string
	'border-top-width'?: string
	'border-width'?: string
	bottom?: string
	'box-align'?: string
	'box-decoration-break'?: string
	'box-direction'?: string
	'box-flex'?: string
	'box-flex-group'?: string
	'box-lines'?: string
	'box-ordinal-group'?: string
	'box-orient'?: string
	'box-pack'?: string
	'box-shadow'?: string
	'box-sizing'?: string
	'break-after'?: string
	'break-before'?: string
	'break-inside'?: string
	'caption-side'?: string
	'caret-color'?: string
	clear?: string
	clip?: string
	'clip-path'?: string
	color?: string
	'color-adjust'?: string
	'color-scheme'?: string
	'column-count'?: string
	'column-fill'?: string
	'column-gap'?: string
	'column-rule'?: string
	'column-rule-color'?: string
	'column-rule-style'?: string
	'column-rule-width'?: string
	'column-span'?: string
	'column-width'?: string
	columns?: string
	contain?: string
	content?: string
	'content-visibility'?: string
	'counter-increment'?: string
	'counter-reset'?: string
	'counter-set'?: string
	cursor?: string
	direction?: string
	display?: string
	'empty-cells'?: string
	filter?: string
	flex?: string
	'flex-basis'?: string
	'flex-direction'?: string
	'flex-flow'?: string
	'flex-grow'?: string
	'flex-shrink'?: string
	'flex-wrap'?: string
	float?: string
	font?: string
	'font-family'?: string
	'font-feature-settings'?: string
	'font-kerning'?: string
	'font-language-override'?: string
	'font-optical-sizing'?: string
	'font-variation-settings'?: string
	'font-size'?: string
	'font-size-adjust'?: string
	'font-smooth'?: string
	'font-stretch'?: string
	'font-style'?: string
	'font-synthesis'?: string
	'font-variant'?: string
	'font-variant-alternates'?: string
	'font-variant-caps'?: string
	'font-variant-east-asian'?: string
	'font-variant-ligatures'?: string
	'font-variant-numeric'?: string
	'font-variant-position'?: string
	'font-weight'?: string
	'forced-color-adjust'?: string
	gap?: string
	grid?: string
	'grid-area'?: string
	'grid-auto-columns'?: string
	'grid-auto-flow'?: string
	'grid-auto-rows'?: string
	'grid-column'?: string
	'grid-column-end'?: string
	'grid-column-gap'?: string
	'grid-column-start'?: string
	'grid-gap'?: string
	'grid-row'?: string
	'grid-row-end'?: string
	'grid-row-gap'?: string
	'grid-row-start'?: string
	'grid-template'?: string
	'grid-template-areas'?: string
	'grid-template-columns'?: string
	'grid-template-rows'?: string
	'hanging-punctuation'?: string
	height?: string
	hyphens?: string
	'image-orientation'?: string
	'image-rendering'?: string
	'image-resolution'?: string
	'ime-mode'?: string
	'initial-letter'?: string
	'initial-letter-align'?: string
	'inline-size'?: string
	inset?: string
	'inset-block'?: string
	'inset-block-end'?: string
	'inset-block-start'?: string
	'inset-inline'?: string
	'inset-inline-end'?: string
	'inset-inline-start'?: string
	isolation?: string
	'justify-content'?: string
	'justify-items'?: string
	'justify-self'?: string
	'justify-tracks'?: string
	left?: string
	'letter-spacing'?: string
	'line-break'?: string
	'line-clamp'?: string
	'line-height'?: string
	'line-height-step'?: string
	'list-style'?: string
	'list-style-image'?: string
	'list-style-position'?: string
	'list-style-type'?: string
	margin?: string
	'margin-block'?: string
	'margin-block-end'?: string
	'margin-block-start'?: string
	'margin-bottom'?: string
	'margin-inline'?: string
	'margin-inline-end'?: string
	'margin-inline-start'?: string
	'margin-left'?: string
	'margin-right'?: string
	'margin-top'?: string
	'margin-trim'?: string
	mask?: string
	'mask-border'?: string
	'mask-border-mode'?: string
	'mask-border-outset'?: string
	'mask-border-repeat'?: string
	'mask-border-slice'?: string
	'mask-border-source'?: string
	'mask-border-width'?: string
	'mask-clip'?: string
	'mask-composite'?: string
	'mask-image'?: string
	'mask-mode'?: string
	'mask-origin'?: string
	'mask-position'?: string
	'mask-repeat'?: string
	'mask-size'?: string
	'mask-type'?: string
	'masonry-auto-flow'?: string
	'math-style'?: string
	'max-block-size'?: string
	'max-height'?: string
	'max-inline-size'?: string
	'max-lines'?: string
	'max-width'?: string
	'min-block-size'?: string
	'min-height'?: string
	'min-inline-size'?: string
	'min-width'?: string
	'mix-blend-mode'?: string
	'object-fit'?: string
	'object-position'?: string
	offset?: string
	'offset-anchor'?: string
	'offset-distance'?: string
	'offset-path'?: string
	'offset-position'?: string
	'offset-rotate'?: string
	opacity?: string
	order?: string
	orphans?: string
	outline?: string
	'outline-color'?: string
	'outline-offset'?: string
	'outline-style'?: string
	'outline-width'?: string
	overflow?: string
	'overflow-anchor'?: string
	'overflow-block'?: string
	'overflow-clip-box'?: string
	'overflow-clip-margin'?: string
	'overflow-inline'?: string
	'overflow-wrap'?: string
	'overflow-x'?: string
	'overflow-y'?: string
	'overscroll-behavior'?: string
	'overscroll-behavior-block'?: string
	'overscroll-behavior-inline'?: string
	'overscroll-behavior-x'?: string
	'overscroll-behavior-y'?: string
	padding?: string
	'padding-block'?: string
	'padding-block-end'?: string
	'padding-block-start'?: string
	'padding-bottom'?: string
	'padding-inline'?: string
	'padding-inline-end'?: string
	'padding-inline-start'?: string
	'padding-left'?: string
	'padding-right'?: string
	'padding-top'?: string
	'page-break-after'?: string
	'page-break-before'?: string
	'page-break-inside'?: string
	'paint-order'?: string
	perspective?: string
	'perspective-origin'?: string
	'place-content'?: string
	'place-items'?: string
	'place-self'?: string
	'pointer-events'?: string
	position?: string
	quotes?: string
	resize?: string
	right?: string
	rotate?: string
	'row-gap'?: string
	'ruby-align'?: string
	'ruby-merge'?: string
	'ruby-position'?: string
	scale?: string
	'scrollbar-color'?: string
	'scrollbar-gutter'?: string
	'scrollbar-width'?: string
	'scroll-behavior'?: string
	'scroll-margin'?: string
	'scroll-margin-block'?: string
	'scroll-margin-block-start'?: string
	'scroll-margin-block-end'?: string
	'scroll-margin-bottom'?: string
	'scroll-margin-inline'?: string
	'scroll-margin-inline-start'?: string
	'scroll-margin-inline-end'?: string
	'scroll-margin-left'?: string
	'scroll-margin-right'?: string
	'scroll-margin-top'?: string
	'scroll-padding'?: string
	'scroll-padding-block'?: string
	'scroll-padding-block-start'?: string
	'scroll-padding-block-end'?: string
	'scroll-padding-bottom'?: string
	'scroll-padding-inline'?: string
	'scroll-padding-inline-start'?: string
	'scroll-padding-inline-end'?: string
	'scroll-padding-left'?: string
	'scroll-padding-right'?: string
	'scroll-padding-top'?: string
	'scroll-snap-align'?: string
	'scroll-snap-coordinate'?: string
	'scroll-snap-destination'?: string
	'scroll-snap-points-x'?: string
	'scroll-snap-points-y'?: string
	'scroll-snap-stop'?: string
	'scroll-snap-type'?: string
	'scroll-snap-type-x'?: string
	'scroll-snap-type-y'?: string
	'shape-image-threshold'?: string
	'shape-margin'?: string
	'shape-outside'?: string
	'tab-size'?: string
	'table-layout'?: string
	'text-align'?: string
	'text-align-last'?: string
	'text-combine-upright'?: string
	'text-decoration'?: string
	'text-decoration-color'?: string
	'text-decoration-line'?: string
	'text-decoration-skip'?: string
	'text-decoration-skip-ink'?: string
	'text-decoration-style'?: string
	'text-decoration-thickness'?: string
	'text-emphasis'?: string
	'text-emphasis-color'?: string
	'text-emphasis-position'?: string
	'text-emphasis-style'?: string
	'text-indent'?: string
	'text-justify'?: string
	'text-orientation'?: string
	'text-overflow'?: string
	'text-rendering'?: string
	'text-shadow'?: string
	'text-size-adjust'?: string
	'text-transform'?: string
	'text-underline-offset'?: string
	'text-underline-position'?: string
	top?: string
	'touch-action'?: string
	transform?: string
	'transform-box'?: string
	'transform-origin'?: string
	'transform-style'?: string
	transition?: string
	'transition-delay'?: string
	'transition-duration'?: string
	'transition-property'?: string
	'transition-timing-function'?: string
	translate?: string
	'unicode-bidi'?: string
	'user-select'?: string
	'vertical-align'?: string
	visibility?: string
	'white-space'?: string
	widows?: string
	width?: string
	'will-change'?: string
	'word-break'?: string
	'word-spacing'?: string
	'word-wrap'?: string
	'writing-mode'?: string
	'z-index'?: string
	zoom?: string
}
